export const CRAWLER_DATA_TYPE_ALL = 'all';
export const CRAWLER_DATA_TYPE_INCREMENTAL = 'incremental';


export const CRAWLER_DATA_TYPE_CHOICES = [
    { id: CRAWLER_DATA_TYPE_ALL, name: `${CRAWLER_DATA_TYPE_ALL}` },
    { id: CRAWLER_DATA_TYPE_INCREMENTAL, name: `${CRAWLER_DATA_TYPE_INCREMENTAL}` },
];
